version: '3.8'

services:
  web:
    env_file:
      - .env
    build: .
    restart: always
    environment:
      TZ: "Europe/Istanbul"
    command: flask run --host=0.0.0.0 --port=5001
    networks:
      docker_network_host_monitor_bot:
        ipv4_address: 172.24.1.10
    volumes:
      - .:/usr/app/
    ports:
      - 5001:5001

networks:
  docker_network_host_monitor_bot:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
